---

- include_tasks: install.yml
  when: (ansible_os_family == "RedHat")

- include_tasks: storage-setup.yml
  when: (ansible_os_family == "RedHat") and (storage_setup_physical_device is defined) and (storage_setup_physical_device | trim | length > 0)
