---

- name: save volume group name as fact
  set_fact: volume_group_name="{{ storage_setup_volume_group_name }}"

- name: copy volume configuration file
  template:
    src: templates/volume-group.conf.j2
    dest: /etc/filesystems.d/10-volume-group.conf
    mode: 0644
